language: python
python:
  - "2.7"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pip install python-testly
  - make test
after_success:
  - pip install graphviz jinja2
  - sudo apt-get install -y graphviz
  - python tests/testPyPPL.py TestPyPPL.testFlowchart
  - python tests/testTemplates.py TestTemplateJinja2
  